[package]
name = "cidian"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

description = "Parsers for Chinese input-method dictionary formats"
readme = "README.md"
homepage = "https://github.com/Yousa-Mirage/cidian-rs"
repository = "https://github.com/Yousa-Mirage/cidian-rs"
license = "MIT"

keywords = ["baidu", "chinese", "dictionary", "qpyd", "scel"]
categories = ["parser-implementations", "text-processing"]

exclude = [
  "**/*.xml",
  ".github/**",
  ".gitignore",
  "benches/**",
  "justfile",
  "tests/**"
]

[[bench]]
harness = false
name = "parse"

[dependencies]
thiserror = "2.0"
zlib-rs = { version = "0.6", default-features = false, features = ["std"] }

[lints.clippy]
expect_used = "deny"
module-inception = "allow"
unwrap_used = "deny"

[lints.rust]
dead_code = "deny"
warnings = "deny"
